version: '3.8'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: localdev
    volumes:
      - ./src/sql/tasks.sql:/docker-entrypoint-initdb.d/01_tasks.sql
    ports:
      - "5432:5432"
