version: '3.8'

services:

  api:
    image: node:21
    working_dir: /home/node/app
    env_file:
      - ./.env
    environment:
      POSTGRES_HOST: db
    volumes:
      - ./src:/home/node/app/src
      - ./package.json:/home/node/app/package.json
    ports:
      - "3000:3000"
    command: bash -c "echo 'Node app starting...' && npm install && npm run dev"

  db:
    image: postgres:16-alpine
    env_file:
      - ./.env
    volumes:
      - ./src/sql/tasks.sql:/docker-entrypoint-initdb.d/01_tasks.sql
    ports:
      - "5432:5432"
